### ISSUE TITLE
Array Overflow

### ISSUE THREAD

**Issue by 8RATH** [yni2yni/TSM16C#1]
In your newest version, ADS_Touch_Sensor_TSM16C_20210216.ino, the array "read_data" does not have sufficient size.
Using read_data[3] will have unpredictable result, in my case, read_data[3](which is that dodgy out of bound byte) is always 0x14, no matter what I do to the touchpad.
Also, consider use git's version control instead of having a ton of files? Git is a VCS after all.
A simple git diff will be able to identify this issue, since the definition of the array is different from the last version, with no good reason. Maybe you copied this from your TSM12 library without checking carefully?

 line 131,  byte read_data[3] = {0}; // should be read_data[4]

**Comment by yni2yni** [comment]
Yes. What you said is correct. thank you
Setting the array to [4] is correct. This is my mistake.
